// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/aether.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vector2 for position and velocity
type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_proto_aether_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Full state of an entity
type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vec2                  `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Rotation      float32                `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	LastUpdate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_proto_aether_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{1}
}

func (x *EntityState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityState) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityState) GetVelocity() *Vec2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntityState) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *EntityState) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

// Represents a change in an entity's state
type MovementDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vec2                  `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Rotation      float32                `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovementDelta) Reset() {
	*x = MovementDelta{}
	mi := &file_proto_aether_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovementDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementDelta) ProtoMessage() {}

func (x *MovementDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementDelta.ProtoReflect.Descriptor instead.
func (*MovementDelta) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{2}
}

func (x *MovementDelta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MovementDelta) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MovementDelta) GetVelocity() *Vec2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *MovementDelta) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *MovementDelta) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Input from client to server
type ClientInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VelocityX     float32                `protobuf:"fixed32,1,opt,name=velocity_x,json=velocityX,proto3" json:"velocity_x,omitempty"`
	VelocityY     float32                `protobuf:"fixed32,2,opt,name=velocity_y,json=velocityY,proto3" json:"velocity_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInput) Reset() {
	*x = ClientInput{}
	mi := &file_proto_aether_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInput) ProtoMessage() {}

func (x *ClientInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInput.ProtoReflect.Descriptor instead.
func (*ClientInput) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{3}
}

func (x *ClientInput) GetVelocityX() float32 {
	if x != nil {
		return x.VelocityX
	}
	return 0
}

func (x *ClientInput) GetVelocityY() float32 {
	if x != nil {
		return x.VelocityY
	}
	return 0
}

// Batch of entities for a client
type WorldSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Deltas        []*MovementDelta       `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"` // Optimization: only send changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_proto_aether_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{4}
}

func (x *WorldSnapshot) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *WorldSnapshot) GetDeltas() []*MovementDelta {
	if x != nil {
		return x.Deltas
	}
	return nil
}

var File_proto_aether_proto protoreflect.FileDescriptor

const file_proto_aether_proto_rawDesc = "" +
	"\n" +
	"\x12proto/aether.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\xc8\x01\n" +
	"\vEntityState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\bposition\x18\x02 \x01(\v2\v.proto.Vec2R\bposition\x12'\n" +
	"\bvelocity\x18\x03 \x01(\v2\v.proto.Vec2R\bvelocity\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x02R\brotation\x12;\n" +
	"\vlast_update\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\"\xc7\x01\n" +
	"\rMovementDelta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\bposition\x18\x02 \x01(\v2\v.proto.Vec2R\bposition\x12'\n" +
	"\bvelocity\x18\x03 \x01(\v2\v.proto.Vec2R\bvelocity\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x02R\brotation\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"K\n" +
	"\vClientInput\x12\x1d\n" +
	"\n" +
	"velocity_x\x18\x01 \x01(\x02R\tvelocityX\x12\x1d\n" +
	"\n" +
	"velocity_y\x18\x02 \x01(\x02R\tvelocityY\"m\n" +
	"\rWorldSnapshot\x12.\n" +
	"\bentities\x18\x01 \x03(\v2\x12.proto.EntityStateR\bentities\x12,\n" +
	"\x06deltas\x18\x02 \x03(\v2\x14.proto.MovementDeltaR\x06deltasB&Z$github.com/yourname/aethersync/protob\x06proto3"

var (
	file_proto_aether_proto_rawDescOnce sync.Once
	file_proto_aether_proto_rawDescData []byte
)

func file_proto_aether_proto_rawDescGZIP() []byte {
	file_proto_aether_proto_rawDescOnce.Do(func() {
		file_proto_aether_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aether_proto_rawDesc), len(file_proto_aether_proto_rawDesc)))
	})
	return file_proto_aether_proto_rawDescData
}

var file_proto_aether_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_aether_proto_goTypes = []any{
	(*Vec2)(nil),                  // 0: proto.Vec2
	(*EntityState)(nil),           // 1: proto.EntityState
	(*MovementDelta)(nil),         // 2: proto.MovementDelta
	(*ClientInput)(nil),           // 3: proto.ClientInput
	(*WorldSnapshot)(nil),         // 4: proto.WorldSnapshot
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_aether_proto_depIdxs = []int32{
	0, // 0: proto.EntityState.position:type_name -> proto.Vec2
	0, // 1: proto.EntityState.velocity:type_name -> proto.Vec2
	5, // 2: proto.EntityState.last_update:type_name -> google.protobuf.Timestamp
	0, // 3: proto.MovementDelta.position:type_name -> proto.Vec2
	0, // 4: proto.MovementDelta.velocity:type_name -> proto.Vec2
	5, // 5: proto.MovementDelta.timestamp:type_name -> google.protobuf.Timestamp
	1, // 6: proto.WorldSnapshot.entities:type_name -> proto.EntityState
	2, // 7: proto.WorldSnapshot.deltas:type_name -> proto.MovementDelta
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_aether_proto_init() }
func file_proto_aether_proto_init() {
	if File_proto_aether_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aether_proto_rawDesc), len(file_proto_aether_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_aether_proto_goTypes,
		DependencyIndexes: file_proto_aether_proto_depIdxs,
		MessageInfos:      file_proto_aether_proto_msgTypes,
	}.Build()
	File_proto_aether_proto = out.File
	file_proto_aether_proto_goTypes = nil
	file_proto_aether_proto_depIdxs = nil
}
